name: PureFactions
version: '@version@'
authors: [DanTheTechMan, Pasarus, Caibinus, Callum, Richardhyy, Mitras2, Kaonami, GoodLucky777, Elafir, Deej, VoChiDanh, alyphen]
main: dansplugins.factionsystem.MedievalFactions
api-version: 1.13
softdepend: [dynmap, PlaceholderAPI, Fiefs]
description: This Minecraft plugin allows players to organize themselves into feudal, diplomatic, lawful groups akin to nations.

commands:
  pf:
  f:
  purefactions:
  factions:

permissions:
  pf.claim:
    default: true
  pf.unclaim:
    default: true
  pf.unclaimall:
    default: true
  pf.checkclaim:
    default: true
  pf.autoclaim:
    default: true
  pf.version:
    default: true
  pf.addlaw:
    default: true
  pf.ally:
    default: true
  pf.breakalliance:
    default: true
  pf.chat:
    default: true
  pf.checkaccess:
    default: true
  pf.create:
    default: true
  pf.declareindependence:
    default: true
  pf.declarewar:
    default: true
  pf.demote:
    default: true
  pf.desc:
    default: true
  pf.disband:
    default: true
  pf.duel:
    default: true
  pf.editlaw:
    default: true
  pf.gate:
    default: true
  pf.grantindependence:
    default: true
  pf.help:
    default: true
  pf.home:
    default: true
  pf.info:
    default: true
  pf.invite:
    default: true
  pf.invoke:
    default: true
  pf.join:
    default: true
  pf.kick:
    default: true
  pf.laws:
    default: true
  pf.leave:
    default: true
  pf.list:
    default: true
  pf.lock:
    default: true
  pf.makepeace:
    default: true
  pf.members:
    default: true
  pf.power:
    default: true
  pf.promote:
    default: true
  pf.removelaw:
    default: true
  pf.rename:
    default: true
  pf.revokeaccess:
    default: true
  pf.sethome:
    default: true
  pf.swearfealty:
    default: true
  pf.transfer:
    default: true
  pf.unlock:
    default: true
  pf.vassalize:
    default: true
  pf.who:
    default: true
  pf.prefix:
    default: true
  pf.flags:
    default: true
  pf.bypass:
    default: op
  pf.config:
    default: op
  pf.unclaim.others:
    default: op
  pf.disband.others:
    default: op
  pf.resetpowerlevels:
    default: op
  pf.force.*:
    default: op
  pf.force.save:
    default: op
  pf.force.load:
    default: op
  pf.force.peace:
    default: op
  pf.force.demote:
    default: op
  pf.force.join:
    default: op
  pf.force.kick:
    default: op
  pf.force.power:
    default: op
  pf.force.renounce:
    default: op
  pf.force.transfer:
    default: op
  pf.force.removevassal:
    default: op
  pf.force.rename:
    default: op
  pf.force.bonuspower:
    default: op
  pf.force.unlock:
    default: op
  pf.force.create:
    default: op
  pf.force.claim:
    default: op
